### ISSUE TITLE
Readmd.md Y-Offset Mentioned twice

### ISSUE THREAD

**Issue by KanoCodez** [GlueGunStanley/Stretcher#1]
When mentioning how to configure the location for custom vehicles it states the Y-offset when talking about the Z-offset

`xOffset determines the position of the stretcher in the vehicle to the left or right relative to the vehicle.`
`yOffset determines the position of the stretcher in the vehicle to the front or rear relative to the vehicle.`
`yOffset determines the position of the stretcher in the vehicle higher or lower in height relative to the vehicle.`

It should say: 
`zOffset determines the position of the stretcher in the vehicle higher or lower in height relative to the vehicle.`

**Comment by GlueGunStanley** [comment]
Thanks for bringing this to my attention, this has been corrected.
